cabal-version: 3.0
name: circuits-int
version: 0.1.0.0
license: BSD-3-Clause
license-file: LICENSE
copyright: Tony Day (c) 2026
category: control
author: Tony Day
maintainer: tonyday567@gmail.com
homepage: https://github.com/tonyday567/circuits-int#readme
bug-reports: https://github.com/tonyday567/circuits-int/issues
synopsis: Int construction and polynomial functors for circuits
description:
  Experimental companion library to @circuits@.  Contains the Int
  construction ('Circuit.Int') and polynomial-functor sketches
  ('Circuit.Poly') that were formerly part of the core @circuits@
  package.

build-type: Simple
tested-with:
  ghc ==9.14.1

source-repository head
  type: git
  location: https://github.com/tonyday567/circuits-int

common ghc-options-stanza
  ghc-options:
    -Wall
    -Wno-unused-imports
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wpartial-fields
    -Wredundant-constraints

common ghc2024-additions
  default-extensions:
    DataKinds
    DerivingStrategies
    DisambiguateRecordFields
    ExplicitNamespaces
    GADTs
    LambdaCase
    MonoLocalBinds
    RoleAnnotations

common ghc2024-stanza
  if impl(ghc >=9.10)
    default-language:
      GHC2024
  else
    import: ghc2024-additions
    default-language:
      GHC2021

library
  import: ghc-options-stanza
  import: ghc2024-stanza
  hs-source-dirs: src
  exposed-modules:
    Circuit.Int
    Circuit.Poly
    Circuit.Poly.DiffP
    Circuit.Poly.Mealy

  build-depends:
    base >=4.18 && <5,
    circuits >=0.3 && <0.4,
    circuits-ad >=0.1 && <0.2,
    mealy >=0.5 && <0.6,

test-suite spec
  import: ghc-options-stanza
  import: ghc2024-stanza
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  hs-source-dirs: test
  build-depends:
    base >=4.18 && <5,
    circuits >=0.3 && <0.4,
    circuits-int,
    circuits-ad,
    mealy,
    numhask,
  default-language: GHC2024
